name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Static compile check
        run: |
          python -m py_compile server.py
      - name: Import and build app
        run: |
          python - << 'PY'
          import server
          app = server.build_app()
          assert app is not None
          print('OK: app built')
          PY
