name: Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      supabase_url:
        description: 'Supabase URL (optional override)'
        required: false
      app_name:
        description: 'App name (FastCloud)'
        required: false
        default: 'burnsdb'

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Note
        run: |
          echo "Deployment is managed by FastMCP Cloud via GitHub integration."
          echo "Connect this repo in the FastCloud UI and set env vars + start command."
          echo "This workflow exists only for manual checks or future automation."
