name: Deploy to FastMCP Cloud

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Set environment variables (with defaults if not provided)
    env:
      APP_NAME: ${{ vars.APP_NAME || 'burns-database' }}
      PORT: ${{ vars.PORT || '8080' }}
      ENABLE_DIAG: ${{ vars.ENABLE_DIAG || 'true' }}
      BASE_URL: ${{ vars.BASE_URL || 'https://burns-database.fastmcp.app' }}

      # Secrets and other config
      BDB_AUTH_TOKEN: ${{ secrets.BDB_AUTH_TOKEN }}
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install FastMCP Cloud CLI and Dependencies
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # Install the FastMCP Cloud CLI (`fastcloud` command)
          pip install fastmcp-cloud
          # Ensure the CLI is available
          command -v fastcloud || { echo "FastMCP Cloud CLI (fastcloud) not found in PATH"; exit 1; }
          # Install jq for JSON parsing in later steps
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Deploy to FastMCP Cloud
        shell: bash
        run: |
          set -euo pipefail
          # Use the FastMCP Cloud CLI to deploy
          APP_NAME_FIXED="${APP_NAME:-burnsdb}"
          PORT_FIXED="${PORT:-8080}"

          fastcloud deploy \
            --app "${APP_NAME_FIXED}" \
            --start "uvicorn server:app --host 0.0.0.0 --port ${PORT_FIXED}" \
            --env APP_NAME="${APP_NAME_FIXED}" \
            --env PORT="${PORT_FIXED}" \
            --env ENABLE_DIAG="${ENABLE_DIAG}" \
            --env BDB_AUTH_TOKEN="${BDB_AUTH_TOKEN}" \
            --env SUPABASE_URL="${SUPABASE_URL}" \
            --env SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY}" \
            --env OPENAI_API_KEY="${OPENAI_API_KEY}" \
            --env EDGEOFN_AUTH_MODE="service_role"

      - name: Set healthcheck route (best effort)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          # Configure the healthcheck endpoint for the FastMCP app
          fastcloud healthcheck set --app "${APP_NAME:-burnsdb}" --path "/mcp" || true

      - name: Verify /mcp/health endpoint
        shell: bash
        run: |
          set -euo pipefail
          # Try up to 5 times to get a 200 OK from the health endpoint
          code="000"
          for attempt in {1..5}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Bearer ${BDB_AUTH_TOKEN}" \
              "${BASE_URL}/mcp/health" || true)
            if [ "$code" = "200" ]; then
              echo "Health check OK (received HTTP 200)."
              break
            fi
            echo "Health not ready (got $code). Retrying in 5 seconds..."
            sleep 5
          done
          if [ "$code" != "200" ]; then
            echo "Health check failed (last HTTP code $code)."
            exit 1
          fi

      - name: Verify Supabase connectivity
        shell: bash
        run: |
          set -euo pipefail
          # Call the /mcp/tools/supabase_health endpoint to check Supabase connections
          response=$(curl -sS -X POST \
            -H "Authorization: Bearer ${BDB_AUTH_TOKEN}" \
            -H "Content-Type: application/json" \
            "${BASE_URL}/mcp/tools/supabase_health")
          echo "Supabase health response: $response"

          # Use jq to assert that auth_ok and rest_ok are true in the JSON response
          echo "$response" | jq -e '.auth_ok and .rest_ok' > /dev/null
          echo "Supabase connectivity: auth_ok = $(echo "$response" | jq -r '.auth_ok'), rest_ok = $(echo "$response" | jq -r '.rest_ok')"
